# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e77c68748df487fb05b2649364c82e526e798787fae8014f4dec6c8fced977898cfdb1a033633b66a9f70f5d82ae622f0ab4d700d2ed339baaa7c94aa618730

test:
  secret_key_base: 54cfdcd463dbcb37a97067baee39870dc35f35792e320badfff2564cb959be20fce8c47ea8913de6717fa198a80f579f400ea9ad43751fc8e5fa692b927de123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
